name: 02 - workflow Event

on: 
    push:
    pull_request:
    workflow_dispatch:
    # schedule: 
    #   - cron: '0 0  * * *'

jobs: 
    echo: 
        runs-on: ubuntu-latest
        steps: 
            - name: show the trigger
              run: echo "the job was triggered by ${{ github.event_name }}"
