name: 03-workflow-runner

on: push 

jobs: 
    ubuntu-echo: 
        runs-on: ubuntu-latest
        steps: 
            - name: ubuntu runner os
              run: | 
                echo "print ubuntu runner os name"
                echo "Runner OS: $RUNNER_OS"
                df -h 
                free -m 
                lsblk 

    windows-echo: 
        runs-on: windows-latest
        steps: 
            - name: windows runner os
              shell: bash
              run: |  
                echo "Print windows runner name"
                echo "Runner OS: $RUNNER_OS"
                df -h 

    mac-echo: 
        runs-on: macos-latest
        steps: 
            - name: mac runner os 
              run: | 
                echo "Print mac runner os name"
                echo "Runner OS: $RUNNER_OS"
                df -h 
