name: 03-workflow-runner

on: push 

jobs: 
    ubuntu-echo: 
        runs-on: ubuntu-latest
        steps: 
            - name: ubuntu runner os
              run: | 
                echo "print ubuntu runner os name"
                echo "Runner OS: $RUNNER_OS"
